### ISSUE TITLE
Empty AAAA response when ipv6 is not enabled

### ISSUE THREAD

**Issue by SviMik** [tklauser/llmnrd#10]
Just caught a packet that doesn't look right. I guess it should ignore AAAA requests if ipv6 is not enabled. And it shouldn't send response when it has no IP address of given type :)

![llmnrd_empty_response](https://cloud.githubusercontent.com/assets/12394507/18015118/e3865b7c-6bce-11e6-9bce-1c1a879eef78.png)

**Comment by tklauser** [comment]
Thanks for the report! Will commit a fix shortly...
