### ISSUE TITLE
Debian packaging files

### ISSUE THREAD

**Issue by elazarl** [tklauser/llmnrd#12]
Hi,

Are you interested with a PR adding `debian` folder to enable deb file packaging?

This would allow users to run `debuild` from the root directory and create a debian package.

And thanks for the great work. Debian Jessie's systemd doesn't have LLMNR yet, and your project makes it much easier to add LLMNR for a linux box.

**Comment by tklauser** [comment]
Yes, sure. I'd gladly merge such a PR.

Thanks!
