### ISSUE TITLE
llmnrd: consider restricting daemon privilegies via systemd service directives

### ISSUE THREAD

**Issue by andhe** [tklauser/llmnrd#16]
Hi.

Still not very familiar with llmnrd, but would be nice to have it tightly restricted to limit potential attack surface. This can easily be done via systemd Protect*, Restrict*, etc directives.

See https://www.youtube.com/watch?v=hiW8eIdcRgo

I haven't (yet) read the source of llmnrd, but took a guess at what you might want to add under the [Service] section:

ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectControlGroups=true
PrivateTmp=true
PrivateDevices=true
PrivateNetwork=false
PrivateUsers=true
#RootDirectory=.... to chroot
RestrictAddressFamilies=AF_NETLINK AF_INET AF_INET6
ProtectKernelModules=true
MemoryDenyWriteExecute=true

For full explanation of these please see https://www.freedesktop.org/software/systemd/man/systemd.directives.html

**Comment by tklauser** [comment]
Very interesting indeed. I guess llmnrd would have to assume a minmum systemd release in case of using these? Maybe I should just include them in the service files as commented-out examples so users could use them if they have a new enough systemd...
