### ISSUE TITLE
llmnrd: Provide init script

### ISSUE THREAD

**Issue by tklauser** [tklauser/llmnrd#2]

**Comment by tklauser** [comment]
Also see #3

**Comment by diego-santacruz** [comment]
Just in case this is an init script that works well in our application (OE-Core). I added the txt extension to be able to attach it.

[llmnrd-init-script.txt](https://github.com/tklauser/llmnrd/files/5200975/llmnrd-init-script.txt)

**Comment by tklauser** [comment]
@diego-santacruz awesome. Feel free to send a PR adding this file to this repos `etc/` directory (where the systemd service file already resides), so the contribution can be properly attributed.
