### ISSUE TITLE
llmnr-query prints garbage characters

### ISSUE THREAD

**Issue by tbetker** [tklauser/llmnrd#22]
`log_info("LLMNR response: %s IN %s %s (TTL %d)\n", name, ...)` prints some uninitialized data because `name` is not NUL-terminated. See the attached patch for a possible fix.

[llmnr-query-fix-missing-nul.patch.txt](https://github.com/tklauser/llmnrd/files/805126/llmnr-query-fix-missing-nul.patch.txt)

**Comment by tklauser** [comment]
Thanks a lot for catching this. Patch now applied in commit 29deb4c762.
