### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by mpvader** [tklauser/llmnrd#27]
Hello @tklauser! I've been distracted for a long time; but now back at the original purpose: adding your llmnrd to [Venus OS](https://github.com/victronenergy/venus/wiki).

For building I need the latest patches: can you tag & release a new version?

Thanks in advance.

**Comment by mpvader** [comment]
Never mind; I checked your repo 5 orso days ago; and today did not recheck before typing this issue.

By some incredible coincidence; after both not doing anything in the last 11 months; you made a release in between.

thanks!

**Comment by tklauser** [comment]
Hi @mpvader. What a coincidence 😄 I've been intending to do a new release for quite a while but never found the time. Thanks for raising this!
