### ISSUE TITLE
bind to specific interface option requires root privileges

### ISSUE THREAD

**Issue by jvfranklin** [tklauser/llmnrd#29]
Trying to use the -i option to bind to a specific interface fails unless it's running as root:
[jon@jonf llmnrd]$ ./llmnrd -H idrac -i ens192
Starting llmnrd on port 5355, hostname idrac
Binding to interface ens192
Error: Failed to bind socket to device ens192: Operation not permitted
[jon@jonf llmnrd]$ sudo ./llmnrd -H idrac -i ens192
[sudo] password for jon: 
Starting llmnrd on port 5355, hostname idrac
Binding to interface ens192
Added IPv4 address 100.69.127.109 on interface ens192

I've tracked this down to the use of the SO_BINDTODEVICE socket option.  I've got a patch I can submit for this.

**Comment by tklauser** [comment]
Sure, please feel free to send a PR to address this. Thanks.

**Comment by tklauser** [comment]
Fixed by #30.
